version: '3'
services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - selector
      - player
  
  player:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  selector:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity